In [1]:
import numpy as np
np.__version__

'1.13.3'

In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [6]:
L2 = list(str(c) for c in L)
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [12]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]
# Each item is a Python object

[bool, str, float, int]

In [14]:
import array
L = list(range(10))
A = array.array('i', L)
# The 'i' is a type code indicate the contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# ---------------------------------------------------------------------- #

In [17]:
# Creating array from python lists.
# Integer array
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [18]:
np.array([3.14, 4, 2, 3])
# Numpy will upcast automatically, eg, int->float

array([ 3.14,  4.  ,  2.  ,  3.  ])

In [19]:
np.array([1,2,3,4,5], dtype='float32')

array([ 1.,  2.,  3.,  4.,  5.], dtype=float32)

In [20]:
np.array([range(i, i+3) for i in [1, 4, 7]])
# Numpy array can also be a multidimensional array by using list of list.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# ---------------------------------------------------------------------- #

In [21]:
# Creating array from scrach
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones(10, dtype=float)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [23]:
np.zeros((3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
np.ones((5,5), dtype=float)

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [25]:
np.full((3,3), 25)

array([[25, 25, 25],
       [25, 25, 25],
       [25, 25, 25]])

In [26]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
# Create an array of 4 values evenly spaced between 1 and 10
np.linspace(1, 10, 4)

array([  1.,   4.,   7.,  10.])

In [29]:
# Create a 3x3 array of uniformly distributed
# Random values between 0 and 1
np.random.random((3, 3))

array([[ 0.72051543,  0.52612042,  0.32301372],
       [ 0.20348812,  0.28821489,  0.7477728 ],
       [ 0.8398353 ,  0.26267958,  0.385763  ]])

In [31]:
# Create a 3x3 array of normally distributed random values 
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (5, 5))

array([[ 0.41500562,  0.76524303, -0.54899517,  0.34276889,  0.40024129],
       [ 0.72236299,  0.48635827,  0.99391272, -0.01855963,  1.36423851],
       [-0.33608423, -0.39376718,  0.17176299, -2.18634556, -0.95271121],
       [-0.619127  ,  0.13703256, -0.06237161,  1.52605145,  0.64193608],
       [ 0.15397105, -0.84129584, -0.2356368 , -0.3379437 ,  0.83082763]])

In [32]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(50, 100, (3, 3))

array([[96, 54, 63],
       [76, 80, 68],
       [96, 83, 88]])

In [33]:
# Create a 3x3 identity matrix
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [34]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that 
# memory location
np.empty(3)

array([ -1.28822975e-231,   1.73060058e-077,  -2.32035601e+077])

In [ ]:
# ---------------------------------------------------------------------- #