In [ ]:
# ---------------------------------------------------------------------- #

In [2]:
# Numpy array attributes.
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6) # one-dimensional array
x2 = np.random.randint(10, size=(3,4)) # two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [6]:
print("x3 ndim: ", x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype: ", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


In [8]:
x1

array([5, 0, 3, 3, 7, 9])

In [9]:
x1[0]

5

In [10]:
x1[0] = 3.1415
# this will be truncated.

In [11]:
x1

array([3, 0, 3, 3, 7, 9])

In [13]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5] # first 5 elements

array([0, 1, 2, 3, 4])

In [15]:
x[5:] # all the elements after index 5

array([5, 6, 7, 8, 9])

In [16]:
x[4:7] # slicing from index 4 to 7

array([4, 5, 6])

In [17]:
x[::2] # even index

array([0, 2, 4, 6, 8])

In [18]:
x[1::2] # odd index

array([1, 3, 5, 7, 9])

In [19]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [21]:
x2[:2,:3] # 2 row, 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [24]:
x2[:, 0] # first column of x2

array([3, 7, 1])

In [25]:
x2[0, :] # first row of x2 == x2[0]

array([3, 5, 2, 4])

In [28]:
grid = np.arange(1,10).reshape((3,3)) # put number 1 through 9 to 3*3 grid.
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x = np.array([1,2,3,4])
x.reshape((1,4)) # equal to x[np.newaxis, :]

array([[1, 2, 3, 4]])

In [36]:
x.reshape((4,1)) # equal to x[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [4]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.concatenate([x, y])
z

array([1, 2, 3, 4, 5, 6])

In [5]:
w = np.concatenate([x,y,z])
w

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

In [6]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [12]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
