In [1]:
import numpy as np

In [9]:
M = np.ones((2,3))
a = np.arange(3)
print(M)
print(a)
print("M.shape =", M.shape)
print("a.shape =", a.shape)

[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[0 1 2]
M.shape = (2, 3)
a.shape = (3,)


In [10]:
X = np.random.random((10, 3))
print(X)

[[ 0.83816689  0.14101576  0.42679484]
 [ 0.57356432  0.55970888  0.014874  ]
 [ 0.8810515   0.23201905  0.41277018]
 [ 0.97049221  0.78113475  0.22034725]
 [ 0.36471474  0.38477556  0.90329284]
 [ 0.61562418  0.16413364  0.74577332]
 [ 0.40279939  0.52813011  0.68686853]
 [ 0.64139036  0.4677648   0.30523615]
 [ 0.24083888  0.55593685  0.02738386]
 [ 0.73407097  0.48444573  0.99207433]]


In [18]:
Xmean = X.mean(0)
Xmean

array([ 0.62627134,  0.42990651,  0.47354153])

In [19]:
X_centered = X - Xmean
X_centered

array([[ 0.21189554, -0.28889075, -0.04674669],
       [-0.05270702,  0.12980236, -0.45866753],
       [ 0.25478016, -0.19788746, -0.06077135],
       [ 0.34422086,  0.35122824, -0.25319428],
       [-0.2615566 , -0.04513095,  0.42975131],
       [-0.01064716, -0.26577287,  0.27223179],
       [-0.22347196,  0.0982236 ,  0.213327  ],
       [ 0.01511902,  0.03785828, -0.16830538],
       [-0.38543247,  0.12603034, -0.44615767],
       [ 0.10779963,  0.05453922,  0.5185328 ]])

In [20]:
X_centered.mean(0)

array([  5.55111512e-17,  -1.11022302e-17,   2.22044605e-17])